allowBuilds:
  "@sentry/cli": false
  "@swc/core": false
  cloudflared: true
  esbuild: true
  protobufjs: false
  sharp: false
minimumReleaseAgeExclude:
  - '@ait-co/debug-console@0.1.1'
  - '@ait-co/debugger@0.1.1'
